- tests/configs/recommended.test.ts
- tests/package.test.ts
These are the only files missing coverage.
> test: coverage on plugin and recommended config

- build.config.ts
- package.json
- scripts/postbuild.ts
- src/index.ts
- yarn.lock
- Fix types in package.json causing package to masquerade as ESM
- Change the default export to be a more helpful name to avoid import-x/no-rename-default.
- Fix incorrect default export in CJS due to a known issue with unbuild.
> fix: plugin types are wrong in CJS

- package.json
- src/etc/could-be-function.ts
- src/etc/could-be-type.ts
- src/etc/get-type-services.ts
- src/etc/index.ts
- src/rules/no-unsafe-subject-next.ts
- src/rules/throw-error.ts
- tests/etc/could-be-type.test.ts
- tests/etc/create-source-file-and-type-checker.ts
- yarn.lock
- Remove unmaintained `tsutils` and `tsutils-etc`.
- `tsutils` has been replaced by the community with `ts-api-utils`. See https://github.com/ajafff/tsutils/issues/145.  Replacing it was fairly simple.
- `tsutils-etc` relies on `tsutils`, and I haven't seen a community-chosen replacement, so we're re-implementing the utilities into this repo, similar to how we re-implemented `eslint-etc` utilities.  So utilities now exist in `ts-api-utils`, but `couldBeType` and `couldBeFunction` had to be ported over.
- Pull in a dev dependency on `@typescript/vfs` to unit test `couldBeType` based on the `tsutils-etc` unit tests for that function.
- Bump the minimum versions of TypeScript to >=4.2.0 to align with `ts-api-utils` and `tslib` to ^2.1.0 to align with `rxjs`.
> fix: remove tsutils and tsutils-etc

- CHANGELOG.md
- eslint.config.mjs
- package.json
- src/etc/could-be-function.ts
- src/etc/could-be-type.ts
- src/etc/get-loc.ts
- src/etc/get-type-services.ts
- src/rules/no-cyclic-action.ts
- src/rules/no-unsafe-subject-next.ts
- src/rules/throw-error.ts
- tests/etc/could-be-type.test.ts
- tests/etc/create-source-file-and-type-checker.ts
- yarn.lock
`import * as ts from "typescript"` does not work as expected in ESM until TypeScript 5.5 (see https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#easier-api-consumption-from-ecmascript-modules).  This was causing projects using an ESM eslint config with TypeScript 4.7 through 5.4 to get:
```
Oops! Something went wrong! :(
ESLint: 8.57.1
TypeError: Cannot read properties of undefined (reading 'Any')
```
This changes to `import ts from "typescript"` so the import works on those older TypeScript versions in ESM.
- Also increase minimum TypeScript version to 4.7.4 to align with `typescript-eslint/typescript-estree`'s supported versions.
> fix: broken imports in esm + typescript <5.5

- docs/rules/no-ignored-replay-buffer.md
- src/rules/no-ignored-replay-buffer.ts
- tests/rules/no-ignored-replay-buffer.test.ts
Fixes https://github.com/cartant/eslint-plugin-rxjs/issues/100
There's also a proposed fix PR in the upstream repo https://github.com/cartant/eslint-plugin-rxjs/pull/114 but I avoided looking at that solution to avoid any license issue, so this solution might be different.
- Fix: if the `shareReplay` operator was passed an object config, then require `bufferSize` to be in that object.
- Fix: the rule wasn't handling if `shareReplay` is imported under a namespace.
- (Might need to review the entire project.  Since rxjs now recommends importing from "rxjs" instead of "rxjs/operators", there's a risk that many rules also fail to account for that new paradigm.  Note that this rule is the only rule that tests namespace imports for all cases, so we at least should expand that coverage/type of …
> fix(no-ignored-replay-buffer): check config bufferSize

- README.md
- docs/rules/macro.md
- src/rules/macro.ts
The [`babel-plugin-rxjs-tools`](https://www.npmjs.com/package/babel-plugin-rxjs-tools) package is unmaintained (and never left prerelease).  This PR deprecates the lint rule requiring use of that package.
If there are no objections, this rule will be removed before the release of v1.
> chore: deprecate rxjs-x/macro

- src/etc/get-type-services.ts
- src/rules/no-cyclic-action.ts
- src/rules/no-unbound-methods.ts
- src/rules/no-unsafe-subject-next.ts
- src/rules/throw-error.ts
These utility functions are unused or replaceable with built-in `ESLintUtils.getTypeServices` or `ts-api-utils`.
> refactor: remove unnecessary functions from getTypeServices

- README.md
- docs/rules/throw-error.md
- src/rules/throw-error.ts
- tests/rules/throw-error.test.ts
- Resolves #21 .  Removes functionality that was linting regular js `throw` statements.  Users should prefer https://typescript-eslint.io/rules/only-throw-error/ instead.
- Added options to disallow `any` and `unknown` if users want stricter checking.
- Moved the report node to the return body of the factory instead of the whole function itself.
- Reworked tests to prioritize testing passing a factory function to `throwError` instead of a raw value, because rxjs has deprecated the latter.
> feat(throw-error)!: stop linting throw statements

- README.md
- docs/rules/ban-operators.md
- src/rules/ban-operators.ts
- tests/rules/ban-operators.test.ts
BREAKING CHANGE: this rule now requires typed linting.
- Resolves #7 .  Reworked `ban-operators` to support banning operators imported from root "rxjs" too.
- This uses typed linting to actually check the operator's type instead of just reading the import statement.  This was done based on the original maintainer's comments in the unit tests indicating this was necessary.
- Also resolves upstream https://github.com/cartant/eslint-plugin-rxjs/issues/96 .  Banned operators are now reported at the area they're used in the code instead of the import statement.
- This allows developers to `eslint-disable-next-line` to allow banned operators more precisely.
- This also resolves the only blocker before #8 can be worked.
- NOTE: this only runs inside of `pipe()` due to performance reasons.
- If …
> feat(ban-operators)!: type check, report in place

- README.md
- docs/rules/no-ignored-default-value.md
- src/index.ts
- src/rules/no-ignored-default-value.ts
- src/rules/no-ignored-replay-buffer.ts
- tests/rules/no-ignored-default-value.test.ts
Introduces a new rule that enforces `defaultValue` to be passed into `firstValueFrom`, `lastValueFrom`, `first`, and `last`, in order to prevent `EmptyError`.
Resolves upstream https://github.com/cartant/eslint-plugin-rxjs/issues/126
> feat(no-ignored-default-value): new rule for enforcing defaultValue

- docs/rules/no-async-subscribe.md
I frequently see `no-async-subscribe` triggered by developers new to RxJS trying to use Promises.  Additional explanation of this rule is necessary.
> docs(no-async-subscribe): additional explanation

- src/rules/no-ignored-error.ts
- tests/rules/no-ignored-error.test.ts
Fixes lack of error when passing an observer object into `subscribe` that's lacking an `error` property.  Previously this rule would only fire if passing in separate callbacks.
Resolves upstream https://github.com/cartant/eslint-plugin-rxjs/issues/94
> fix(no-ignored-error): check observer object too

- README.md
- docs/rules/no-topromise.md
- src/etc/is.ts
- src/rules/no-topromise.ts
- tests/rules/no-topromise.test.ts
Adds 2 manual editor suggestions to `no-topromise`.  Developers can choose between `lastValueFrom`, which behaves closest to the deprecated `toPromise`, or `firstValueFrom`.
Resolves #37 .
> feat(no-topromise): suggest `lastValueFrom` or `firstValueFrom`

- yarn.lock
https://github.com/advisories/GHSA-3xgq-45jj-v275
> chore(deps-dev): bump cross-spawn from 7.0.3 to 7.0.6

- docs/rules/no-implicit-any-catch.md
- src/rules/no-implicit-any-catch.ts
- tests/rules/no-implicit-any-catch.test.ts
BREAKING CHANGE: allowExplicitAny now defaults to `true` instead of `false`.
This change was made for several reasons:
1. To align with other rules in this codebase dealing with explicit `any` (namely `throw-error`, which allows `any` by default).
2. To align with the rule's name: to a casual reader, this rule seems to only ban implicit `any`, not explicit too.
3. Lax codebases often change allowExplicitAny to `true`, or they disable this rule entirely.
- By relaxing the default options, developers will be encouraged to at least add an explicit annotation, and stricter codebases can re-opt-in to banning `any`.
- Strict codebases likely already have typescript-eslint's no-explicit-any turned on, so this shouldn't reduce practical coverage.
5. The upcoming `strict` config will set this …
> feat(no-implicit-any-catch)!: default to allow explicit any

- package.json
- tests/etc/create-source-file-and-type-checker.ts
- yarn.lock
Uncovered lint error from bumping typescript-eslint from 8.15.0 to 8.16.0.
Also fixes incorrect typescript-eslint warning during `yarn lint-js` about TypeScript 5.7 being unsupported.
> test: fix error msg in unit tests might be [Object object]

- README.md
- docs/rules/no-topromise.md
- docs/rules/prefer-observer.md
- docs/rules/prefer-root-operators.md
- docs/rules/throw-error.md
- package.json
- src/configs/recommended.ts
- src/rules/no-topromise.ts
- src/rules/prefer-observer.ts
- src/rules/prefer-root-operators.ts
- src/rules/throw-error.ts
- tests/package.test.ts
- yarn.lock
BREAKING CHANGE: RxJS ^7.2.0 is required.
BREAKING CHANGE: `recommended` configuration had 4 rules added to it.  See full changelog for details.
Resolves #35 .
- `no-topromise`: `toPromise()` was deprecated by RxJS, so this will be very useful for helping developers migrate to one of the two manual editor suggestions (`lastValueFrom` or `firstValueFrom`).
- `prefer-observer`: RxJS deprecated non-observer object subscribes, so this will help migrate.
- `prefer-root-operators`: RxJS moved operators to root in 7.2.0 and deprecated the old site, so this will help migrate.
- This change requires bumping the RxJS peer dependency to 7.2.0 because 7.0.0 doesn't export the operators from root.
- `throw-error`: This rule will rarely be triggered because it was recently changed to only apply to the …
> feat(recommended)!: add four rules to recommended

- README.md
- docs/rules/no-floating-observables.md
- docs/rules/no-misused-observables.md
- src/configs/strict.ts
- src/etc/get-type-services.ts
- src/etc/is.ts
- src/index.ts
- src/rules/no-misused-observables.ts
- tests/rules/no-async-subscribe.test.ts
- tests/rules/no-misused-observables.test.ts
New rule based on `@typescript-eslint/no-misused-promises`.  Ensures you don't return an Observable where void is expected, or try to spread an Observable.  This rule is added to the `strict` configuration.
Resolves #43 .
Note: `checksVoidReturn` is noticeably slow, specifically stemming from the `arguments`, `properties`, and `variables` sub-options.  It's still faster than `@typescript-eslint/no-deprecated` and some `import-x` rules, but it's in the top 10 with `TIMING=1` enabled.  But since the implementation is similar to `@typescript-eslint/no-misused-promises` which has similar performance, we'll allow it.
> feat(no-misused-observables): new rule

- .github/dependabot.yml
We're keeping node types in line with the lowest supported Node.js version, so dependabot should ignore all but patch updates.
Also bump PR limit to 10.
> chore(dependabot): don't update node types automatically

- package.json
- src/configs/recommended.ts
- src/configs/strict.ts
- tests/configs/recommended.test.ts
- tests/configs/strict.test.ts
[Configuration name is optional but recommended](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions).  The old eslintrc format does not support name, but since we don't support eslintrc, we're ok to add `name`.
- Add `name` to recommended and strict configurations.  Enforce via unit test.
- Also add more keywords to the npm package as recommended by eslint.org.
> feat: add `name` to each configuration

- package.json
- yarn.lock
BREAKING CHANGE: TypeScript <4.8.4 is no longer supported.
typescript-eslint v8 [dropped support](https://typescript-eslint.io/blog/announcing-typescript-eslint-v8/#tooling-breaking-changes) for TypeScript <4.8.4, and `ts-api-utils` recently did the same in a v2 release.  We are mirroring that change.
> feat(deps)!: bump minimum TypeScript to 4.8.4

- README.md
- docs/rules/no-explicit-generics.md
- src/configs/strict.ts
- src/rules/no-explicit-generics.ts
There are known problems with this rule (#77), so we're removing it to avoid unnecessary problems for now.
> feat(strict): remove no-explicit-generics from `strict`

- LICENSE
When originally forked, we appended text to the copyright notice in `LICENSE`.
It's more proper to add a new line instead of modifying the old one.
Also removing the webpage link as unnecessary.
Resolves #101
> chore(license): add new copyright line

- package.json
- yarn.lock
Public dependency is still 8.1, this is just internal dependency.
> chore(deps-dev): bump internal typescript-eslint to 8.19.1

- docs/rules/no-subject-unsubscribe.md
Adds documentation about previously undocumented (but tested) behavior.  Also adds rule details for this rule.
> docs(no-subject-unsubscribe): document add ban

- docs/rules/no-redundant-notify.md
- src/rules/no-redundant-notify.ts
- tests/rules/no-redundant-notify.test.ts
Adds `unsubscribe` to the logic that guards against sending redundant notifications.
`unsubscribe` is already discouraged by `no-subject-unsubscribe`, but the subscriber argument of `new Observable` could also be affected.  Also, `unsubscribe` technically isn't a "notification", but it's a rare enough use case that it's probably not worth splitting into a separate rule.
Resolves #107
> feat(no-redundant-notify): also catch unsubscribe

- package.json
- yarn.lock
- Drop compatibility for ts-api-utils v1.
- Minimum version of typescript-eslint is now 8.19.1 , to align with their version of ts-api-utils.
- Bumped any related linting dependencies.
Resolves #111
> feat!: bump ts-api-utils to v2

- docs/rules/no-topromise.md
- src/rules/no-topromise.ts
- tests/rules/no-topromise.test.ts
This adds the "most correct" suggestion to `no-topromise` for replacing `toPromise()`.
The old `toPromise()` would resolve to `undefined`, while the new `lastValueFrom` rejects with `EmptyError`. So if a user followed the old top suggestion and replaced `toPromise` with `lastValueFrom`, they might be surprised to find `EmptyError` now thrown instead. This wouldn't be a problem for someone using the `strict` config, which includes `no-ignored-default-value`, but users of the `recommended` config wouldn't get that lint notification.
Resolves #168
> feat(no-topromise): suggest an exact replacement for toPromise()

- src/etc/get-type-services.ts
- tests/rules/finnish.test.ts
- tests/rules/no-finnish.test.ts
- tests/rules/no-misused-observables.test.ts
Fixes `finnish`, `no-finnish`, and `no-misused-observables` failing to check functions with implicit return types.
Resolves #57
> fix: check functions with implicit return types

- package.json
The upstream repo will publish the `docs` folder to npm when published.  But most ESLint plugins nowadays do not do this.  We can gain some space savings by removing `docs` from the published artifacts.
Output from `npm pack` before removing `docs`:
```txt
npm notice package size: 62.7 kB
npm notice unpacked size: 378.7 kB
```
After removing `docs`:
```txt
npm notice package size: 48.4 kB
npm notice unpacked size: 298.8 kB
```
> chore: stop publishing docs to npm

- docs/rules/no-explicit-generics.md
- src/etc/is.ts
- src/rules/no-explicit-generics.ts
- tests/rules/no-explicit-generics.test.ts
Now something like the following will be allowed:
```ts
const subject = new BehaviorSubject<ISomeType | null>(null);
```
This addresses #77
> Fix #77 - Allow explicit union types on `no-explicit-generics` rule

- docs/rules/no-unbound-methods.md
- src/constants.ts
- src/rules/no-unbound-methods.ts
- tests/rules/no-unbound-methods.test.ts
Adds a new option `allowTypes` to the rule `no-unbound-methods` so users may specify specific types that are safe to pass unbound.
By default, we set it to `Signal` to support Angular's signals out of the box.
Resolves #209 and upstream https://github.com/cartant/eslint-plugin-rxjs/issues/137
> feat(no-unbound-methods): allow unbound signals

- docs/rules/no-async-subscribe.md
- src/rules/no-async-subscribe.ts
- tests/rules/no-async-subscribe.test.ts
Adds support for catching `next: async () => ...` properties when passing an object into `subscribe`.
This may cause a significant increase in reports for this rule, because previously we were not checking observer objects at all and `prefer-observer` may have been pushing codebases to migrate to observer objects.  So this also enhances the `forbidden` message to include a snippet from this rule's docs, so that intellisense is more useful.
Resolves #163
> fix(no-async-subscribe): report async next properties on observer object

- src/rules/no-implicit-any-catch.ts
- tests/rules/no-implicit-any-catch.test.ts
We're assuming that if `callback` has more than one parameter (i.e. `restParams.length > 0`), then all the parameters should already be wrapped in parenthesis (or else it's invalid JS syntax), so we can safely insert `: unknown` and nothing else.
Resolves #224
> fix(no-implicit-any-catch): proper parenthesis for two-param catchError
